# Generated by Django 5.1.1 on 2024-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
