# Generated by Django 5.1.1 on 2024-10-13 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_region_region_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='photosreviewhotel',
            name='review',
        ),
        migrations.RemoveField(
            model_name='photosreviewkitchen',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewattraction',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='reviewattraction',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reviewhotel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reviewhotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='reviewkitchen',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reviewkitchen',
            name='kitchen',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='like',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_reviews', to='store.attractions'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='store.hotel'),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to='store.kitchen'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('attraction', 'Attraction'), ('place', 'Place')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photosreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='places',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_places', to='store.places'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Плохо'), (2, 'Удовлетворительно'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoryevent')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='store.places')),
            ],
        ),
        migrations.DeleteModel(
            name='PhotosReviewAttraction',
        ),
        migrations.DeleteModel(
            name='PhotosReviewHotel',
        ),
        migrations.DeleteModel(
            name='PhotosReviewKitchen',
        ),
        migrations.DeleteModel(
            name='ReviewAttraction',
        ),
        migrations.DeleteModel(
            name='ReviewHotel',
        ),
        migrations.DeleteModel(
            name='ReviewKitchen',
        ),
    ]
