# Generated by Django 5.1.1 on 2024-10-13 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categoryevent_remove_photosreviewhotel_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_photos', to='store.review'),
        ),
    ]
