# Generated by Django 5.1.1 on 2024-10-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_photosreview_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='image',
        ),
    ]
