# Generated by Django 5.1.1 on 2024-10-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_attractions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='at_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='at_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='at_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='game_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='game_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='game_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='handcraft_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='handcraft_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='handcraft_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='category_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='category_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='category_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='meal_time_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='meal_time_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='meal_time_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='name_kitchen_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='name_kitchen_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='name_kitchen_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='specialized_menu_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='specialized_menu_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='specialized_menu_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='nationalfood_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='nationalfood_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='nationalfood_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='instrument_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='instrument_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='instrument_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='places_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='places_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='places_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ar',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='description_name_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='description_name_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='description_name_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='food_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='food_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='food_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='include_food_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='include_food_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='include_food_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_ar',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_en',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_ru',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
