# Generated by Django 5.1.1 on 2024-10-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_attractions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='at_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='at_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='game_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='game_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='handcraft_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='handcraft_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='category_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='category_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='meal_time_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='meal_time_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='name_kitchen_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='name_kitchen_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='specialized_menu_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='specialized_menu_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='nationalfood_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalfood',
            name='nationalfood_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='instrument_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='instrument_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='places_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='places_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_tr',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='description_name_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='description_name_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='food_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='food_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='include_food_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionfood',
            name='include_food_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_en',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_tr',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
